# Catalog data is generated by zsh.nix from the alias definitions.
_dotfiles_runtime_help() {
  local raw_name name expansion
  while IFS= read -r raw_name; do
    name="${(Q)raw_name}"
    [[ -n "${_dotfiles_managed_abbrs[$name]-}" ]] && continue
    expansion="$(abbr expand "$name" 2>/dev/null)" || continue
    if [[ "$1" == catalog ]]; then
      printf '%s\t%s\t%s\t%s\0' "$name" 'Runtime abbreviations' "$expansion" "$name = $expansion"
    else
      print -r -- "$name = $expansion"
    fi
  done < <(abbr list-abbreviations 2>/dev/null)
}

_dotfiles_help() {
  local mode="$1" content runtime_content
  shift
  if [[ "$mode" == commands ]]; then
    content="$_dotfiles_help_commands"
  else
    content="$_dotfiles_help_descriptions"
  fi
  runtime_content="$(_dotfiles_runtime_help text)"
  if [[ -n "$runtime_content" ]]; then
    content+=$'\n\n[Runtime abbreviations]\n'"$runtime_content"
  fi
  if (( $# )); then
    print -r -- "$content" | rg -i --color=never -- "$*"
  else
    print -r -- "$content"
  fi
}

_dotfiles_help_catalog() {
  local entry
  for entry in "${_dotfiles_help_entries[@]}"; do
    printf '%s\0' "$entry"
  done
  _dotfiles_runtime_help catalog
}

hp() {
  local selected result
  selected="$(_dotfiles_help_catalog | fzf --read0 --print0 +m --no-print-query --no-expect --reverse --height 80% \
    --delimiter=$'\t' --with-nth=1,2,3 --nth=1,2,3 --query="$*" \
    --prompt='Help > ' --header='Enter: help / Esc: close / Shift-Up,Down: scroll preview' \
    --preview='printf "%s\n" {4..}' --preview-window='right,60%,wrap' \
    --bind='shift-up:preview-up,shift-down:preview-down')"
  result=$?
  (( result == 1 || result == 130 )) && return 0
  (( result == 0 )) || return "$result"
  selected="${selected%$'\0'}"
  [[ -n "$selected" ]] || return 0
  # Drop the three list columns. The remaining text is help, never shell code.
  selected="${selected#*$'\t'}"
  selected="${selected#*$'\t'}"
  print -r -- "${selected#*$'\t'}"
}

h() {
  if (( $# == 0 )) && [[ -t 0 && -t 1 ]] && (( $+commands[fzf] )); then
    hp
  else
    _dotfiles_help descriptions "$@"
  fi
}

hv() { _dotfiles_help commands "$@"; }

devg() {
  local ghq_root repo
  ghq_root="$(ghq root 2>/dev/null || printf '%s\n' "$HOME/Develop")"
  repo="$(
    (
      ghq list -p
      find "$ghq_root/local" -maxdepth 1 -mindepth 1 -type d
    ) 2>/dev/null | awk '!seen[$0]++' | fzf --reverse --height 40%
  )"
  [[ -n "$repo" ]] && cd "$repo"
}

_dotfiles_workspaces() {
  local manifest
  # Prune cloned repositories and metadata, including legacy ghq symlinks.
  while IFS= read -r -d '' manifest; do
    printf '%s\0' "${manifest:h}"
  done < <(find "$1" -type d \( -name repos -o -name .git -o -name node_modules \) -prune \
    -o -type f -name repos.json -print0)
}

wsg() {
  if (( $# > 1 )); then
    print -u2 -- 'Usage: wsg [root]'
    return 2
  fi
  local workspace_root="${1:-$HOME/Workspaces}" selected result
  workspace_root="${workspace_root:a}"
  if [[ ! -d "$workspace_root" ]]; then
    print -u2 -- "Workspace directory does not exist: $workspace_root"
    print -u2 -- 'Create one with: ws init ~/Workspaces/product'
    return 1
  fi
  # Buffer candidates into a temp file before fzf so arrow-key input is not
  # interleaved with a slow find stream. NUL delimiters are kept so paths with
  # newlines remain intact.
  selected="$(
    local tmp
    tmp="$(mktemp "${TMPDIR:-/tmp}/wsg-candidates.XXXXXX")" || exit 2
    trap 'rm -f -- "$tmp"' EXIT INT TERM
    _dotfiles_workspaces "$workspace_root" > "$tmp" || exit 1
    fzf --read0 --print0 +m --no-print-query --no-expect --reverse --height 40% \
      --prompt='Workspace > ' --header='Enter: change directory / Esc: cancel' < "$tmp"
  )"
  result=$?
  (( result == 1 || result == 130 )) && return 0
  (( result == 0 )) || return "$result"
  selected="${selected%$'\0'}"
  [[ -n "$selected" ]] || return 0
  [[ -f "$selected/repos.json" ]] || return 1
  cd -- "$selected"
}
